### ISSUE TITLE
Content Reference Swaps

### ISSUE THREAD

**Issue by awanczowski** [perfectsense/dari#150]
Hi All, 

I am trying to find an easy way to swap out all references to a piece of content. I can find all the references to a piece of content by querying 

`Query<Content> query = Query.from(Content.class).where("* matches ?", original.getId());` 

Once i find a match I want to take the state object and find each field that references the original. Once I find all the fields I would like to swap out the original object with a replacement of a valid type. Does anyone know of an easy way to do this? 

Thanks
Drew

**Comment by hyoolim** [comment]
I'm closing this issue for now, as there hasn't been any activity in some time, but if you're still having problems, please feel free to reopen.

Going forward, we'll be more closely monitoring the issues here so that the questions don't go unanswered for so long.
