### ISSUE TITLE
Image handler incorrectly returns image/jpg content-type

### ISSUE THREAD

**Issue by nickdunn** [perfectsense/dari#276]
We've experienced an issue (using v2.4 of Dari) whereby JPEGs are served with a mime type of `image/jpg`, when it should be `image/jpeg`. IE11 aborts requests for `image/jpg` (https://www.bennadel.com/blog/2609-internet-explorer-aborts-images-with-the-wrong-mime-type.htm).

https://github.com/perfectsense/dari/blob/b127435a91d39e1f2a63e536dbc79429bd140e52/image/src/main/java/com/psddev/dari/util/JavaImageServlet.java#L55

**Comment by AndrewJMiller** [comment]
Thanks for reporting this Nick, I've logged it as a bug and am testing the fix.
We will comment back here when the fix has been merged and give you the latest build number of 2.4
