### ISSUE TITLE
Update JavaDoc on Query.get/setTimeout()

### ISSUE THREAD

**Issue by gmazza** [perfectsense/dari#280]
The Dari documentation has getTimeout() and setTimeout() methods listed but no definition of what the "double" value means -- is it seconds or milliseconds or?  what does the .setTimeout(30) mean for example?

http://www.dariframework.org/javadocs/com/psddev/dari/db/Query.html#getTimeout()

**Comment by rhino88** [comment]
Thanks for the feedback gmazza, I've submitted a PR with some updates to the javadocs.
