### ISSUE TITLE
Brightspot. MySQL and PostgreSQL: UnsupportedIndexException

### ISSUE THREAD

**Issue by olgadichkovskaya** [perfectsense/dari#306]
I got the exception on both databases:
`Can't render /cms/dashboardWidget/default/com.psddev.cms.tool.widget.RecentActivityWidget/bbf6360b-12a6-3c9d-8ccd-60bc3e5d9894!

com.psddev.dari.db.UnsupportedIndexException: [_any] field is not indexed in [SqlDatabase]! (com.psddev.dari.util.AggregateException)
com.psddev.dari.db.AggregateDatabase.read(AggregateDatabase.java:322)
com.psddev.dari.db.AggregateDatabase.readPartial(AggregateDatabase.java:352)
com.psddev.dari.db.ForwardingDatabase.readPartial(ForwardingDatabase.java:93)
Toggle Stack Traces
Parameters:
_=1496325493174
`

Cms version: 3.3-SNAPSHOT. I use maven archetype for creating project and examples from https://github.com/perfectsense/brightspot-tutorial.

**Comment by olgadichkovskaya** [comment]
![image](https://cloud.githubusercontent.com/assets/28594256/26684555/f4937074-46ef-11e7-93ce-125376f74d53.png)

**Comment by olgadichkovskaya** [comment]
![bsp](https://cloud.githubusercontent.com/assets/28594256/26713958/c3fef31a-4777-11e7-8db3-cb690645091e.png)

**Comment by vitdo82** [comment]
+1

**Comment by olgadichkovskaya** [comment]
My configuration for MySQL:
`
    <Environment name="dari/defaultDatabase" type="java.lang.String" value="brightspot" override="false"/>
    <Environment name="dari/database/brightspot/class" override="false" type="java.lang.String" value="com.psddev.dari.db.AggregateDatabase"/>
    <Environment name="dari/database/brightspot/defaultDelegate" override="false" type="java.lang.String" value="sql"/>
    <Environment name="dari/database/brightspot/delegate/sql/class" override="false" type="java.lang.String" value="com.psddev.dari.db.SqlDatabase"/>

<Resource name="dari/database/brightspot/delegate/sql/dataSource"
              auth="Container"
              type="javax.sql.DataSource"
              driverClassName="com.mysql.jdbc.Driver"
              url="jdbc:mysql://localhost:3306/brightspot"
              username="root"
              password="root"
              logAbandoned="true"
              maxActive="100"
              maxIdle="30"
              maxWait="10000"
              removeAbandoned="true"
              removeAbandonedTimeout="60"
              testOnBorrow="true"
              validationQuery="SELECT 1"/>
`
