### ISSUE TITLE
HOWTO know if a content object is new or saved in database?

### ISSUE THREAD

**Issue by tankchintan** [perfectsense/dari#53]
I have an api that creates a new or updates an existing content object. I directly deserialize the JSON payload in to the conten object.

The way I want to differentiate between a new and old object is if the `id` is set or not. But when I do `content.getId()` I always get an UUID regardless of whether it was an old or new object.

I checked the `Record.java` code & it seems that `getId()` return a new UUID if none is set.

So what would be the figure out whether new or old?

Is `content.getState().isNew()` the way to go?

**Comment by Ryan-Anderson** [comment]
`#isNew()` will return true if the state has never been saved to the database. That should cover your use case.

**Comment by tankchintan** [comment]
@Ryan-Anderson Thanks!
