### ISSUE TITLE
Data processing taking long time

### ISSUE THREAD

**Issue by ajayaks** [perfectsense/dari#72]
I am using Solr as source for reading data and noticed Dari apis are sending multiple queries to Solr on every call of below methods.

Using these functions query.select(offset,maxrecords) and query.selectAll() . Database is set to SolrDatabase.

If i am making direct query to Solr at debug/db_solr with same query that are producing after calling above function, its taking 15 ~30 ms.
Now the problem is via Query.select() and Query.selectAll() its executing queries against Solr with the actual required query hence increasing the response time (about 1500ms).

I would like to understand why its sending extra queries and how to improve the response time. I have verified everything on my side and this is the main area which is causing delay in response.

Please suggest , thanks in advance.

More precisely, in SolrDatabase below seems causing long time:-
queryPartialWithOptions ->createSavedObjectWithDocument().

What is the baseline speed for above operations ?

Please suggest,

**Comment by hyoolim** [comment]
I'm closing this issue for now, as there hasn't been any activity in some time, but if you're still having problems, please feel free to reopen.

Going forward, we'll be more closely monitoring the issues here so that the questions don't go unanswered for so long.
